#!/bin/bash

python3 -m ckernel install ckernel "C/C++"

#Change Julia Kernel (1.10)
jupyter notebook --generate-config
echo "c.MultiKernelManager.default_kernel_name = 'C/C++'" >> /home/jovyan/.jupyter/jupyter_notebook_config.py
echo "c.MappingKernelManager.default_kernel_name = 'C/C++'"  >> /home/jovyan/.jupyter/jupyter_notebook_config.py
echo "c.AsyncMultiKernelManager.default_kernel_name = 'C/C++'"  >> /home/jovyan/.jupyter/jupyter_notebook_config.py
echo "c.AsyncMappingKernelManager.default_kernel_name = 'C/C++'"  >> /home/jovyan/.jupyter/jupyter_notebook_config.py
echo "c.GatewayKernelManager.default_kernel_name = 'C/C++'"  >> /home/jovyan/.jupyter/jupyter_notebook_config.py

exec "$@"
